version: '3.7'
services:
  php:
    image: app-php
    build:
      context: .
      target: app_php
    depends_on:
      - db
    volumes:
      - .:/srv/api:rw
    networks:
      - yii2_network

  api:
    image: app-nginx
    build:
      context: .
      target: app_nginx
    depends_on:
      - php
    volumes:
      - ./web:/srv/api/web:ro
    ports:
      - "80:80"
    networks:
      - yii2_network

  db:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
      - .:/srv/api:rw,cached
      - ./dumps:/srv/dumps
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=default
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
    networks:
      - yii2_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret
      UPLOAD_LIMIT: 300M

volumes:
  dbdata: {}
  esdata:
    driver: local

networks:
  yii2_network:
    driver: bridge